//=============================================================================
// RMMZ - Typescript Plugin Archetype
//=============================================================================

/*:
 *
 * @target MZ
 * @plugindesc Typescript Plugin Archetype.
 * @author Comuns
 * 
 * @help Typescript Plugin Archetype.
 * 
 * This is a plugin archetype, it does not provide any functionality, only a
 * template for other plugins.
 *
 */

//=============================================================================
// ** NOTICE **
//-----------------------------------------------------------------------------
// The code below is generated by a compiler, and is not well suited for human
// reading. If you are interested on the source code, please take a look at
// the Github repository for this plugin!
//=============================================================================
